### ISSUE TITLE
Export outputs as json

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-utils#15]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

It would be nifty if we could export the output of this module as a raw JSON file so it can be downloaded and parsed via `jq`.

**Comment by Nuru** [comment]
```
terraform output -json
```
